[program:worker-reverb]
process_name=%(program_name)s_%(process_num)02d
command=bash -c 'exec php /app/artisan reverb:start --host=0.0.0.0 --port=8080'
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
startsecs=0
stdout_logfile=/var/log/worker-reverb.log
stderr_logfile=/var/log/worker-reverb.log
